baseURL = "https://codethoi.com"
languageCode = "vi-vn"
title = "Khánh's Blog | Code Thối"
theme = "m10c"
paginate = 15
enableRobotsTXT = true
[params]
  name = "Khánh Trắng"
  jobTile = "Code Thối"
  author = "Khanh, Lai Van"
  description = "Blog này là nơi mình chia sẻ những kiến thức, kinh nghiệm mà mình đạt được trong quá trình làm việc và trải nghiệm. Và cả những dòng code THỐI nữa :))"
  keywords = ["code","clean code","code thoi","code thối","chia sẻ kiến thức","cấu hình","java developer","fullstack developer"]
  metaData = "a123123"
  facebookAppId = ""
  facebookAdminsId = ""
  googleSiteVerification = "wo64O86TdUrMxfsofpwf5VlbUIjjvXHZzDY5abf0ts0"
  bingSiteVerification = "080A9672F801279C0E50510383971A10"
  yandexSiteVerification = "db9fa7ec4316d628"
  pinterestSiteVerification = "850152a3ed5a57309482eb4111f8267b"
  googleAnalytics = "UA-137826165-1"
  [[params.social]]
    name = "github"
    url = "https://github.com/khanhlv"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/khanhlv4"
  [[params.social]]
    name = "facebook"
    url = "https://fb.com/khanhlv4"

[params.style]
  lightestColor = "#ffffff"
  lightColor = "#a2a2a2"
  primaryColor = "#008b8b"